
[master]
name            = "Phase Gate Manager"
tags            = ["Must be run on server", "Gameplay tweak", "Tool"]
autodescription = true
description     = "README.md"
preview         = "preview.png"

[beta]
name            = "Phase Gate Manager - Beta"
tags            = ["Must be run on server", "Gameplay tweak", "Tool"]
autodescription = true
description     = "README.md"
preview         = "preview.png"
